
<!-- DENA Project -->

```{r echo=FALSE, results='asis'}
project("dena", 3)
```

The distance education needs analysis project was a project delegated to my cohort (n = 5, including myself) during our ESM Seminar course. To be honest, I had mixed feelings about the project. On the one hand, I saw its importance. The analysis could provide valuable insight into designing a program responsible for educating dozens of evaluators. On the other hand, it seemed much of the curriculum was already planned out and the use of the evaluation results would be minimal. This, combined with the fact that the project was already pre-designed with minimal input from my cohort, did not make me feel motivated about the project.

  Nevertheless, I certainly learned from this project. First, I learned a lot about doing qualitative research. As a qualitative project, the main method was interviewing. While I had some practice in interviewing, this was my first experience at applying it to a non-classroom-based project. I only conducted three interviews (due to lack of response and the project occuring during a pandemic), but I think I improved a number of key interviewing skills. Though we all followed an interview protocol, I made sure to use probing and follow-up questions to help the interviewee clarify and explain their thoughts. Probing and follow-ups of this nature were not in the protocol. I found that during the interviews, while I could have moved on after their comments provided a surface-level answer to the question, I felt that probing deeper (using some of the prompts I learned in Introduction to Qualitative Research) helped me get richer data and a better understanding of what interviewees were trying to say. I think that having these experiences, few as they may have been, will be valuable for any future interviewing I do, few as that may also be, too.
  
  Another skill I was able to exercise was project management. Specifically, flexibility was key here for a number of reasons. First, as a team with disparate interests, availability, and skills, the project needed to remain flexible enough to accommodate us all while still being goal-driven. This meant being strategic about using class time periods for meetings and for delegating or volunteering for work that fit within our wheelhouses while still pushing the project forward. For example, I used my tech-savviness to build one of our participant contact lists (which required automatic and manual webscraping). I also used my data visualization skills to develop the visuals for our final deliverable.
  
  Flexibility in timing was also key. This was a multi-semester project and moved at a very slow pace - something I am not very comfortable with. To me, when a project is slow, my interest wanes very quickly. It nearly died with this project. We were slow in getting organized, getting the IRB approved, building contact lists, contacting participants, getting interviews, analyzing, and writing. The pandemic began around the time we had planned to collect data. This did not affect our data collection methods, as we had always planned Zoom interviews, but it did increase the timeline of our project. Knowing that my participation in the project was still important because it was a group project, and that the results had potential real impact on the proposed program, I remained flexible and, most importantly, patient. I reminded myself of the proverb "slow and steady wins the race". Cliché as the proverb may be, telling myself this was important as a reminder that there was absolutely no need to rush, and that rushing often leads to sloppy results.
  
  The lessons I learned in flexibility and adapting to team needs amid a  crisis while staying goal-oriented are certainly crucial aspects of project management skills. Interestingly, project management skills were some of the key skills interviewees stated evaluators needed to be successful! It was quite "meta" to deal with project management issues in an evaluation while at the same time hearing them emerge during an interview on creating an evaluation program. I certainly concur and appreciated the conceptual reinforcement this project wrought.
