
```{r echo=FALSE, results='asis'}
project("fairchance", 3)
```

The Fair Chance proposal was one of the final products of EDPY 651 Advanced Evaluation. It was also my best evaluation experience to date, even though the project involved only the development of a proposal and not actual implementation.

It was my best evaluation experience because it was a real-world task (responding to an actual request for proposal [RFP]) that required me to synthesize my previous course work in evaluation, statistics, and qualitative research while working as part of a small team. As part of one of my final courses in the ESM program, the assignment felt like a capstone project in which all the skills from my previous coursework was needed. I very much enjoyed the opportunity to synthesize them.

The RFP called for an impact evaluation of one of Fair Chance's (a Washington, D.C.-based nonprofit) capacity building programs, which assists other nonprofits in organizational leadership and growth. The process of reading and responding to the RFP was a rigorous exercise in creativity, methodological thinking, and project management. The entire proposal required creative thinking in order to help us design an evaluation approach that made sense for the client's needs. We had to make sure that lenses of social justice, cultural responsiveness, and methods that lead to evaluation use pervaded to proposal.

Creative thinking also lead to methodological thinking, as we had to consider the most logical and efficient approaches to the evaluation design (we chose a mixed methods explanatory approach) and which methods would realistically answer the evaluation questions. My primary role was in this latter regard, and I believe I developed a robust mixed methods evaluation plan that considers descriptive (both quantitatively and qualitatively), inferential, and causal analyses while dealing with small sample sizes and longitudinal data. 

In order to develop these approaches, I drew on the successes and failures from previous quantitative projects (especially the PhD Student Conferences project, see below). For example, I thought through what the data would look like if it were open in R Studio, and what steps I would have to take to answer the specific questions presented in the RFP. I stopped short of actually simulating the data but rather ran through specific scenarios in my head, including what data visualizations would look like (as interactive dashboards and as part of a final report) and how this would help the client understand the impact of their program. Likewise, as I was designing an explanatory mixed methods analysis, I thought of potential results and how those could inform the qualitaitve phase of the study. I then thought through the sequence of qualitaitve work and the order in which it should proceed (i.e. from focus groups to interviews in order to mirror a general to specific approach). Logical, step-by-step thought experiments were essential to creating a proposal that received *exceptionally high praise* from Dr. Skolits.

In terms of project management, two different processes were involved. First, there was thinking through the timeline, budget, and communication plan of the RFP. This was lead by my partner and fellow ESM student, Sarah Narvaiz, but required my contribution and feedback, too. Second, was the actual management of the proposal assignment Sarah and I were the only two students to approach an RFP together; all others worked independently. While there are many advantages to teamwork, it also presents several challenges including division of labor, keeping to deadlines, and making sure team members are on the "same page" conceptually. What helped us was that we were in constant contact with each other either through Zoom or through Slack. We set meetings to discuss the evaluation and to agree on approaches; chose roles that suited our strengths; set timelines for drafts, feedback, and revisions; and developed final deliverables together. I believe the fact that we worked as a team and were therefore accountable to someone other than ourselves improved the quality of our project, making it one of the best in the class. In fact, Dr. Skolits referred to our evaluation as "very mature, solid, and I think a highly competitive proposal" and at the same level of quality as actual evaluation firms.

To be fair, not all aspects of the project were positive. What stuck out the most to me was the actual search for a relevant RFP that we could use for our project. I did not enjoy the RFP search process at all. I have already had poor experiences gaining funding for small research projects. Searching for big-ticket projects that may be responsible for funding my entire organization (and my entire salary) is just not for me. The risk and stress is just too high. I know that if I continue to pursue a career in academia, grant writing may be in my future; however, for it to be a primary facet of what I am working on is something that I do not think is in my nature. I am more interested in methods, data, and analysis - not begging for funding. I realize this is a bit dramatic and that it is necessary for many jobs, inside and outside of academia. I also recognize this does not necessarily preclude me from evaluation work, as I could still work as an analyst. Still, the search for an RFP does move my personal Evaluation, Statistics, and Measurement/Methodology needle closer to the S and M and away from the E. It also makes me rethink a future career in academia, where I may need to dedicate more energy to gaining funding rather than to research (or teaching).

Just to illustrate this point, I formerly worked for a self-funded academic institution on campus. If I wanted to attend any professional development session or conference, I had to seek funding outside the organization. This meant an exorbitant amount of time was spent searching, applying, and hoping for funding, leaving actual participation in PD sessions or conference in an ever-present and anxiety-filled "up in the air" status. While I was often successful in gaining funding, this was always stressful. Fast forward a few years and I now work in "industry" (for a non-profit on the peripherals of higher education). One month on the job, when I asked my supervisor if I could attend a conference with a $1,200 registration price, I was never asked to justify attendance, the cost, or anything else. I said, “I’d like to attend…” and my supervisor said, “OK. Book it,” and that was it. No applications. No hoops. That experience made a world of difference in understanding the academia/industry divide and has definitely made me weigh career options more carefully, including the role seeking or maintaining funding will have.

