
```{r echo=FALSE, results='asis'}
project("footprint", 3)
```

The `footprint` R package was a passion project borne out of a research interest in climate change and in needing an easy way to calculate greenhouse gas emissions based on a travel data project I was planning to work on. I have previously mentioned several other projects related to my interest in climate change and education (STARS, PhD Student Conferences, Sustainable Energy Working Group, University Air Travel - see section *A. Evaluation and Applied Research Experience*).

In terms of climate change and higher education, academic air travel has been a specific interest of mine. During the 2020 Summer semester, I had planned, as part of a Office of Sustainability internship, to work with UTK travel data. My project would have been to estimate the air travel emissions of faculty, admin, and staff over the past 10 years. Due to issues related to gaining access to this data, the project was put on hold. However, I still planned to follow-up during the 2021 Summer semester. What had become standard practice for me, as detailed in several other reflections, was to imagine what the data would potentially look like and how I would need to go about analyzing it. For this project, I would need some way to take a vector of departure cities and a vector of arrival cities and estimate the greenhouse gas emissions from travel between those two cities. 

There are a number of air travel footprint calculators, some using very sophisticated aircraft size and fuel burn records. However, none to my knowledge could be applied over an entire data set of origin/destination within R (or even Excel). Therefore, I would need to create my own. After doing research on the plethora of methodologies to calculate air travel emissions, I decided to use a data set from the UK's Department for Environment, Food & Rural Affairs (DEFRA), which had an easy to use table that offered per-km emissions estimates for CO~2~, CO~2~e, CH~4~, and NO~x~ at different flight class levels (economy, business, etc.), and for different trip lengths (short, medium, long haul). The research process taught me a great deal about emissions types, differential effects on radiative forcing and climate change, and in general, the different methodologies behind emissions calculations. More importantly, I learned that *all* calculators provide conservative estimates and that it is nearly impossible to get a true measure of travel emissions. Essentially, I would have to be comfortable with ambiguity and a number of assumptions in both the calculation data (e.g. assumptions about plane type, trip length, fuel efficiency, passenger numbers) and in my application of the calculations. For example, lacking true origin data, I would need to make the assumption that traveler left from the city of their home institution. Lacking itinerary information, I need to assume a direct, non-stop flight knowing this is unrealistic. Thus, I can only calculate conservative estimates.

I wrote a function in R that drew on the DEFRA data and calculated emissions based either on longitude/latittude or three-digit airport codes (using the `airportr` package). I was excited about the function and thought it would be a fun project to turn into an R package, as others may find use from it. However, I had never developed an R package before and was a little hesitant to begin on my own. So I reached out to someone on Twitter who I knew also had an interest in data science and climate change, and who had created at least one R package before. It was a data scientist from the UK (Kasia Kulma, PhD). We followed each other on Twitter but had never interacted. I reached out to her via direct message and was pleasantly surprised she was receptive to the idea and willing to work with a complete stranger. We named it the `footprint` package a got to work. Less than a month later, we had a fully functioning package published on CRAN (the official R package server).

I learned a lot from her about R package development and version control using Github. Before this project, I had been a very light user of Github, the gold standard version control platform many software developers (including developers of R packages) use. Github has a web interface but most of the actions to control various software branches, merges, uploads, and downloads are done through a command line using the Git language. I have seen knowledge of Github in many job advertisements, so I am thankful this project gave me some beginner- to intermediate-level experience.

The final step of the project was submission of the `footprint` package to the CRAN package server. Packages are submitted to CRAN and go through a kind of peer review. The peer review is both automated and manual. The automated portion checks that the package works across platforms. The manual review checks to make sure the package is documented clearly and the functions and calculations make sense. My first submission attempt was rejected, as the methodology was not explained clearly enough. My second submission attempt was rejected, as acronyms were not spelled out, more details on the methods were needed, and the example code needed to be fixed. Finally, the third try was the charm and `footprint` was accepted to CRAN in January of 2021.

I am very proud of this package, which as of 2021 May has been downloaded almost 2,000 times. I am excited that this package created a whole new section on my CV, "Software," and look forward to adding more projects to this section. I am also very grateful that this project helped me gain a whole new skill set related to software development, which I know will be very useful for my career in the future.
