
```{r echo=FALSE, results='asis'}
project("gradrates", 3)
```

I developed the paper *Are International Students Getting a Bang for their Buck? The Relationship between Expenditures and International Student Graduation Rates* as part of HEAM 620 Large Data Sets in Education (taught by Dr. Ishitani). My project used IPEDS data on international student graduation rates to measure their relationship to institutional expenditures. This was my first introduction to IPEDS (as well as many other large data sets), a resource I have used consistently since then. It was also my first introduction to concepts such as institutional expenditures. We spent the first three weeks of class reading and critiquing articles that use large data sets, and a number of them used institutional expenditures. These were crucial for developing my research questions and forming a major part of my literature review.

What was most salient about the applied research aspect of this project was the use of theoretical frameworks. I admittedly did not have much experience connecting theory to what I had researched previously. The fact that having a theoretical framework was a requirement of the final project, and the further fact that it is a general requirement of most published academic work, heightened my sensitivity to frameworks in the early readings of the class. As I developed research questions about expenditures, I paid special attention to the theoretical frameworks used in similar research that connected expenditures to student outcomes. This was my first introduction to Astin and his inputs-environment-outcome (IEO) framework [@astinieo]. Astin is a major name in higher education student development research and his framework went a long way in helping me not only frame my research questions but also interpret my results. I have also used Astin's work in later research.

While my gut reaction is often to develop research questions (and methodology) in the absence of a theoretical framework or with an unarticulated theoretical framework that exists mostly at the sub-conscious level, this experience reinforced the importance of having a sound theoretical (or "conceptual," if multiple theories are tied together) framework. This speaks to the importance of having a good grounding in the literature of one's content area. That being said, for someone like myself who is more of a content-area nomad, such grounding is sometimes difficult to achieve. I believe that this project gave me a firm footing in being able to absorb key conceptual models from new content areas relatively quickly, a skill that I will continue to employ.
