```{r echo=FALSE, results='asis'}
project("gradrates", 3)
```

I developed the paper *Are International Students Getting a Bang for their Buck? The Relationship between Expenditures and International Student Graduation Rates* as part of HEAM 620 Large Data Sets in Education (taught by Dr. Ishitani). I introduced this project in sections *A. Evaluation and Applied Research Experience* and *B. Statistical Analysis Experience](Statistical Analysis Experience*. I received excellent feedback on my class presentation and final written product. I took the positive reception of my assignment as a sign that I should try to publish it. I submitted it to the *Journal of International Students* and was pleasantly surprised that they wanted to accept it for publication and only had minor revise and resubmit comments, mostly surface-level revisions.

One comment asked for me to explain the multiple imputation methods I employed with more clarity. This surprised me because my final paper should not have included imputed data! It turned out I had forgotten to replace my initial analyses with the final analyses. I revised my paper, removing the initial analysis and updating all results with the correct models. I felt lucky that my point estimates changed very little from from initial to final analyses and that the interpretations and conclusions did not change at all. I was also very thankful for the peer review process and the comments that pointed out my erroneous inclusion of the wrong data! This made me realize how I should not rush to write manuscripts and how important it is to double- or triple-check one’s work.
