```{r echo=FALSE, results='asis'}
project("gradrates", 3)
```

I developed the paper *Are International Students Getting a Bang for their Buck? The Relationship between Expenditures and International Student Graduation Rates* as part of HEAM 620 Large Data Sets in Education (taught by Dr. Ishitani). I first wrote about this project in section *A. Evaluation and Applied Research Experience*. Besides introducing me to the importance of theoretical frameworks, this project also gave me a chance to apply some advanced statistical concepts while at the same time linking these concepts back to the theoretical framework.

My models were quite straightforward, as I used simple linear regression. Employing this analysis was quite easy, as I was enrolled in Stats III at the same time and had the concepts related to regression and regression diagnostics active in my mind. I also had to do multiple imputation for a chosen covariate in my model (SAT/ACT score). Mulitple imputation was another skill I learned in Stats III and was excited to apply to my own research. Learning how to do regression diagnostics using multiple imputation as well as how to pool data, however, was a concept we didn’t cover in-depth in Stats III, so I struggled a bit to understand how to approach this. Eventually, I found resources on how to calculate pooled regression results and used this for my analyses.

Despite this effort, I decided that my final models did not need the covariates I had imputed. After considering their usefulness, it turned out that they weren’t really specified by the theoretical framework of my model. In particular, as the research focused on international students, including a test they often did not even take seemed unnecessary. While SAT and ACT scores are often included to control for institutional selectivity, they were not part of Astin's student development theories, which underlied my theoretical framework.

In the end, I removed these variables from the model. I learned a lesson in thinking through not only the possible variables to include in an analysis, but whether they were logical or specified by previous theory. Going forward, especially for my dissertation, this will be an important skills to remember.

<!-- I also took the positive reception of my assignment as a sign that I should try to publish it. I submitted it to the *Journal of International Students* and was pleasantly surprised that they wanted to accept it for publication and only had minor revise and resubmit comments. One comment asked for me to explain the multiple imputation with more clarity. This surprised me because my final paper should not have included imputed data! It turned out I had forgotten to replace my initial analyses with the final analyses. -->

<!-- I revised my paper, removing the initial analysis and updating all results with the correct models. I felt lucky that, while the point estimates changed from imputed to non-imputed data, the interpretations and conclusions did not. I was also very thankful for the peer review process and the comments that pointed out my erroneously inclusion of the wrong data! This made me realize how I should not rush to write manuscripts and how important it is to double-check one’s work. -->
