
```{r echo=FALSE, results='asis'}
project("iep", 3)
```


I began working on this project immediately after taking Stats I, before I was officially a student in the ESM program, and while I was employed at UTK’s English Language Institute. From the basic statistics skills that I learned in Stats I, I recognized a way to solve a problem I had been considering at my institute: how effective are we at helping our students succeed at UTK? The best approach to this was to compare students who came to our program first before fully matriculating to UTK (i.e., Intensive English Program [IEP] students) with directly-admitted international students (direct admits). I immediately requested a data set from OIRA to begin piloting an approach to answer this question. My approach was further refined as I began building my statistical skills in Stats II and III, and I finally figured out the best way to answer my research question in the Fall of 2020, after being introduced to equivalence tests.

Throughout this time, I learned about working with institutional data, especially the process for obtaining said data from OIRA. Specifically, I learned the length of time it takes to go from submitting a report request,back-and-forth communications to clarify the request, and  finally receiving the data, all of which takes a long, long time. I also learned the issues that may arise when OIRA does not have complete data. In my case, OIRA did not have access to international student language test scores, which are required for direct admission. This was available through a very lengthy process (about a year) in which I had to work with the admissions office to receive the data. Due to the need to connect admissions data to OIRA data, as well as linking it with data from my own department, I needed student names. Thus, I also learned about the FERPA waiver and was able to successfully get one, which I hear is no easy feat.

By the time of Spring 2019, about one and a half years had passed since I began this project, and I was on my second data set, one with added variables and a larger scope of time. I delivered a presentation of preliminary results at the 2019 TESOL Conference to a large room of about 100+ attendees (see section *E. Presentation Experience*. This was probably the best presentation I had ever given, as the audience response was overwhelmingly positive, with numerous questions throughout and afterward. The feedback also gave me ideas on how to improve my analyses.

By Fall 2019, I requested my final data set, one which included all the key variables I needed and the most recent records available. Unfortunately, there was so much missing data for the test scores that I could not use it as a variable in my final models. During the Spring 2020 semester, I wrote up my final results, consulted with Dr. Rocconi to make sure my equivalence testing method was correct, and sought feedback from content specialists (my former colleagues at the English Language Institute) and my peers (students in the Spring 2020 ESM seminar). The manuscript has undergone numerous revisions, has been reviewed by Dr. Rocconi, and was published as a preprint on *EdArxiv*. So far, it has been rejected from *TESOL Quarterly* (after revisions) and the *Journal of International Students*. Most reviewers have been positive about the manuscript, however, in typical Reviewer 2 fashion, there is always a reviewer who wants me to do a completely different analysis with completely different data. These reviewers have taken issue with using GPA as my dependent variable, even though, as I carefully explain in my manuscript and cover letter, the use of GPA allows me to expand upon prior research, almost all of which has used GPA. I am motivated to get this published, as it is personally meaningful to me. However, the constant rejection is discouraging.

This project taught me several important skills. First, I was able to boost my confidence in and knowledge of quantitative methods, especially regression with moderation and equivalence testing. I learned how to work with institutional data, especially the process of obtaining such data. I also learned the importance of doing pilot analyses, seeking feedback, and presenting preliminary results. This entire project also helped me internalize the idea that research is an iterative rather than linear process.
