
```{r echo=FALSE, results='asis'}
project("resm", 3)
```
The *R Software Handbook* was completed during an internship with Dr. Jennifer Ann Morrow during 2020 Summer. For this internship, the goal was to create a document that ESM students could use to learn R. It had to be both something students could reference or something students could follow from start to finish. Thus, it was part reference manual and part teaching tool. That created an interesting challenge. I had to think about the best sequence to organize each section and its contents in order to build on previous sections and remain both a reference and pedagogical tool. In addition, and more challenging, the text needed to be written in a didactic way that maintained continuity with previous sections and examples. However, it also needed to be easily understood if someone were accessing a section just for reference and had not been following along from the beginning.

I began this project by thinking about how I learned how to use R just six months earlier. I had tried learning R several times prior but often stalled because I had no meaningful application for it. I decided that the handbook should be task-based, with the underlying structure and examples focused on a real-world task: accessing, cleaning, and analyzing messy survey data.

I planned sections on installing and setting up R - often major hurdles for those new to R - and then how to access different types of data. The remainder of the tasks mostly focused on the [R Community Survey](https://github.com/rstudio/r-community-survey), a real-world survey which was coincidentally quite messy.

I used Dr. Morrow's *12 Steps of Data Cleaning* as a guide for organizing the data cleaning section, but also discussed data formats, pivoting data, and data joins - important data "wrangling" skills all R users need to know. Finally, I included a section on data visualization that showed the basic principles of using the `ggplot2` package, used to make high quality visualizations.

One additional challenge during this project was getting my co-author, Austin Boyd, started when he joined the project. He was a welcome addition to the project, contributing the statistical analysis and base R visualization sections. However, I was using a unique format for writing this handbook that allowed text and code to be combined in one document (R Markdown), and the `bookdown` package to put everything together into a web-accessible book format. I was also organizing all of this work online through Github. I had to get Austin up to speed on these tools so that he could contribute easily. I asked him to look at some of my documents to understand a few basics of R Markdown, and met with him via Zoom to show the basics of using Github through RStudio. There were a few hiccups to collaboration, but we were able to finish the handbook in time for the 2020 Fall semester.

Throughout this internship, I learned or reinforced many important skills. I learned better project and time management. I gained experience in thinking about R in a pedagogical way. I a;sp gained valuable practice working with messy survey data needed to illustrate essential R functions. I had to learn a lot of new R functions and packages which I had not previously needed, and then I needed to immediately explain them in a pedagogical way in the handbook. Though at times I was staying "one step ahead of the students" in a sense, the experience was invaluable for enhancing my R skills and also being able to continuously relate to the challenges of learning R.

One other major takeaway from this project was a reawakening of the desire to teach. I had been an English language instructor for international students for about a decade prior to changing careers to something more statistics related (data analysis and visualization). This meant I was no longer in the classroom and no longer thinking about the challenge and creativity involved in teaching. This project reminded me of what I had left behind. I was therefore very happy to eventually develop related workshops on R data visualization and R Markdown, which has allowed me keep a foot in the teaching world while giving me experience in teaching data science-related skills. It has also made me seek out additional experiences combining R and teaching. See *TA for Statistics in Applied Fields III Transition to R* (below) and section *F. Teaching or Supervisory Experience]* reflections on such experiences.
