
```{r echo=FALSE, results='asis'}
project("roffice", 3)
```
For the 2021 Spring semester, I was enrolled in a 33-hour internship with Dr. Rocconi. The purpose of this internship was to help Dr. Rocconi convert his SPSS materials for Applied Statistics III over to R (reflected upon below). In addition, any remaining time would be spent as a TA in the course, holding R office hours and assisting with R-related questions from students (reflected upon in section *F. Teaching or Supervisory/Training Experience*).

My work for the internship began before Spring, during Winter break. I looked through all of Dr. Rocconi’s materials and began developing a guide to R that would be useful as a go-to resource for Stats III students who needed to quickly learn or look up functions that would need to be employed throughout the course. This resource was originally based on an overview of SPSS syntax commands Dr. Rocconi had as a Word file. I kept mostly the same organization and functions, but translated everything to R. I then converted the guide into a portable, interactive webpage that students could conveniently browse. Students could access the document at any time, find a key function using an interactive, floating menu on the left, and see an example of both the code and its output.

I also began working on converting practice assignments and homework over to R. This involved writing R code and modifying Word documents to reflect different R tasks, offer R helper code, or remove tasks that were necessary in SPSS but not in R (and vice versa). Dr. Rocconi later used these as the basis for his own revisions. He typically modified the assignments (reducing or changing tasks) and added onto the code, especially with additional comments and explanation. Though not all of my code or changes were used, I believe they were seen as valuable by Dr. Rocconi, as he could easily use what I made rather than start from scratch.

My work during this internship helped me in several ways. First, by reviewing the Stats III materials, I was able to refresh and recall previous statistical information that I had not remembered or had not used since the semester I took Stats III (in 2019 Spring, two years ago at the time of writing). In a sense, it was an excellent refresher course for me.

Second, when I took Stats III, everything was in SPSS. Although I would currently consider myself an intermediate-level R user, I did not know how to do everything in R that we had done in SPSS. Therefore, there were several methods, functions, and tools I had to learn during this internship. Thankfully, my experience with R gave me a strong foundation on which to do this, so it was not an overwhelming challenge. Still, without the internship, I would not have learned, for example, ANOVA or multiple imputation in R, as I have not used some of these methods “in the wild”. This internship experience has certainly strengthened my R skills, specifically for statistical analyses.
