


```{r echo=FALSE, results='asis'}
project("scope3", 3)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
tribble(
  ~col1, ~col2,
  "Dates:", "2020 Summer - 2020 Fall",
  "Status:", "Complete - Submitted for Publication",
  "Type:", "Applied Research",
  "Data Collection:", "Collection of institutional climate, sustainability, and greenhouse gas mitigation policies",
  "Data Analyses", "Document/Policy Analysis, Thematic Analysis",
  "Brief Description", "The University Air Travel project refers to a project begun as a 2020 Summer internship with the Office of Sustainability. For this internship, I worked on a document/policy analysis project which examined how institutional climate policies addressed (or failed to address) emissions from university air travel. A manuscript has been submitted to the journal *Climate Policy*."
) %>% flextable() %>%
  align(j = "col2", align = "left") %>%
  delete_part(part = "header") %>%
  fontsize(size=12) %>%
  font(fontname = "Times") %>%
  border_remove() %>%
  set_table_properties(layout = "autofit") %>%
  valign(valign = "top", part = "all") %>%
  ftExtra::colformat_md()
```

\newline
