
```{r desc_scope3, echo=FALSE, results='asis'}
project("scope3", 3)
```

This project began as part of an internship with the University of Tennessee's Office of Sustainability, where I was allowed to pursue a project of personal interest that would also be of relevance to the university. For this project, I wanted to know how other university's climate policies addressed greenhouse gas emissions from flying, a growing topic of interest for myself and the greater academic community. It was my hope that such a project could provide useful information about how comparative and aspirational peers addressed this issue and perhaps promote positive changes in UTK's climate action plan and travel policies.

The focus on policies placed me squarely within a qualitative framework for research, and, having just completed Introduction to Qualitative Research, I felt somewhat confident in my ability to pursue this project. The fact that my analysis focused on documents rather than people made the application of what I had learned a little less harrowing in terms of data collection. While there was plenty of downloading and cataloging, there was no need to recruit, interview, and transcribe data. I quickly learned that document analysis was my kind of qualitative research!

I was able to "play" with several methods of coding until I hit upon a system that worked. At first, I had a number of different codes and subcodes, but after reading about half of the documents, broad categories of codes became salient and the rest of the coding was much easier due to the simplified coding structure.

Though I felt confident in the analysis portion of qualitative methods, I still failed to employ several important research activities. Feedback I received as part of submitting my draft manuscript to fellow ESM students indicated that my work lacked trustworthiness (e.g., reliability). I was the sole coder and my codes may have been overly subjective. I reviewed my qualitative textbooks and decided to address this issue via two strategies. First, I sent a sample of documents and my coding scheme to two fellow students and asked them to code the documents with my codes and, if needed, to make new codes. I checked what they had coded against my own and found a great deal of concordance. I also employed member checking, which turned out to be the best strategy in this case. I sent a copy of my manuscript to every institution included and asked them to verify whether the way they were represented correctly. I received three types of responses, all positive. Most institutions confirmed my representation. Several pointed me to documents that had been updated mere months after I had first downloaded them, and several others were excited by this research. They thought that it had practical value and wanted to share my final draft with their office (which I provided).

I cannot claim to necessarily enjoy qualitative research, but, as mentioned in other reflections, I know it is a form of research that can answer important questions - questions that quantitative research cannot. This project gave me more confidence in employing qualitative research methods and showed me a type of qualitative research I would much prefer - document analysis (which, to be honest, is often coupled with interviews and other sorts of human interactions). I learned that team coding and member checking are easy to employ and important methods for establishing reliability. This directly informed some of my approaches to the *Distance Education Needs Analysis* and my *Fair Chance proposal* (see above).

I also believe the feedback I received from fellow students was invaluable and helped to strengthen my manuscript. At the time of writing, the manuscript was just rejected from *Climate Policy* after major revisions were made. I have resubmitted it to the journal *Travel Behaviour and Society*.
