
```{r echo=FALSE, results='asis'}
project("sustainable", 3)
```

I joined the Committee on the Campus Environment after completing an internship for the University of Tennessee's Office of Sustainability (see *"University Air Travel* below). During one of these meetings, it was decided that, in order to meet the university's carbon-neutral goals (100% by 2060), we would need to begin work now on finding ways to decarbonize its energy usage. Thus, the Sustainable Working Energy group was formed, with three subgroups. Knowing that a survey of student attitudes was going to be needed, I volunteered to lead the Student, Faculty, and Staff subgroup.

While the group includes faculty and staff, the immediate focus has been on students because it is their opinions that administration is most interested in. Knowing the broad goals of the working group, our team got to work on a survey. We independently did research on similar surveys and begin drafting items we thought would be useful in answering the group's overarching questions. However, after reviewing the first draft of the survey with a faculty member who was organizing the working groups and had attended meetings in the other subgroups, it was clear there was a misunderstanding of goals. First, our original survey focused exclusively on solar power whereas the group wanted to include wind and biofuels as well, though these are unlikely to be utilized on a large scale for our energy needs. Second, and more importantly, our survey questions did not get at the very specific questions that administration wanted answered, namely to show whether students support or do not support sustainable energy project, and, if so, which ones. The head of the Office of Sustainability (Jay Price), and the head of Facilities Services (Terry Ledford), both of whom would be in charge of relaying results to admin, had these very specific questions in mind that our survey draft was not directly answering. Our team sat down with Jay and Terry and meticulously ran through the draft survey we created, adding, rewording, and removing questions until we had a second draft that met their needs and still left us with additional data for other, less pressing questions. 

I do not think we wasted time with the first draft of the survey, even though it did not fully represent the needs of the working group. It still served as a good repository of working questions. However, I wish we had been given clearer goals, or, on our part, had sought out the key individuals in the first place to make sure we were designing a survey that would be useful for them to take to administration. Because we were all members of the working group, it did not initially feel like there was a stakeholder to consult when clearly there was. A key lesson here is to more carefully consider who stakeholders are, and rather than assuming we know what they want (even if they are on the same team) to seek out and clarify the purposes of the evaluation.

I think that after the revision with Jay and Terry, we have a much better survey draft. The survey and its related recruitment plan are currently under IRB review. We hope to deploy the survey in 2021 Fall. I am quite excited about the survey, and more so about its usage because I believe the results will be in favor of sustainable energy and provide the insight administration needs to move forward with reaching carbon neutrality goals. I hope that I can see the beginnings of these changes during my remaining time at the university.

And unlike previous survey research projects, this one excites me more because I feel confident we can get an ample number of respondents (~3,000). This is because we have the funding to actually offer enticing incentives - a drawing for multiple high-value VolShop gift cards. In the past, I have mostly been involved in survey projects with no incentives and have gotten dismal results. I sincerely hope that the incentives offered with this survey does what research says they should do: get responses. It would not only be beneficial to the survey itself, but it would also boost my waning opinion of survey research in general.
