
```{r echo=FALSE, results='asis'}
project("sustainable", 3)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
tribble(
  ~col1, ~col2,
  "Dates", "2021 Spring to present",
  "Status:", "Ongoing",
  "Type:", "Survey Research",
  "Data Collection:", "Online survey (Qualtrics)",
  "Data Analyses", "Descriptive statistics, survey weighting (raking), and visualizations",
  "Brief Description", "I am leading the Student, Faculty, and Staff subgroup of the Office of Sustainability's Sustainable Energy Working Group. Most of this work involves the design and deployment of a survey for all students during 2021 Fall. Results will be presented to UTK administration to help decide on future sustainable energy projects on campus."
) %>% flextable() %>%
  align(j = "col2", align = "left") %>%
  delete_part(part = "header") %>%
  fontsize(size=12) %>%
  font(fontname = "Times") %>%
  border_remove() %>%
  set_table_properties(layout = "autofit") %>%
  valign(valign = "top", part = "all")
```

\newline
