

```{r list_cse, echo=FALSE, results='asis'}
project("stars", 3)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
tribble(
  ~col1, ~col2,
  "Dates:", "2020 Fall - 2021 Spring",
  "Status:", "Completed - Submitted for Publication",
  "Type:", "Applied Research",
  "Data Collection:", "Secondary Data - Multiple Public Datasets",
  "Data Analyses", "Multilevel Modeling",
  "Brief Description", "This project was initially developed for EDPY 667, Multilevel Modeling. I developed a project which looked at the association between the Sustainability Tracking and Assessment Reporting System (STARS) higher education sustainability rating and political and institutional factors at the county and state level."
) %>% flextable() %>%
  align(j = "col2", align = "left") %>%
  delete_part(part = "header") %>%
  fontsize(size=12) %>%
  font(fontname = "Times") %>%
  border_remove() %>%
  set_table_properties(layout = "autofit") %>%
  valign(valign = "top", part = "all") %>%
  ftExtra::colformat_md()
```

\newline
