
```{r echo=FALSE, results='asis'}
project("stats3", 3)
```

This assignment was the capstone project of EDPY 678 Applied Statistics III (2019 Spring), taught by Dr. Rocconi. It was a project that required students to apply all skills learned from Stats I to Stats III to a real-world data set, write up a technical report as if it were for a real client, and present the data in a similar manner. The work was done in groups that consisted of one or two ESM students (myself and a fellow student) and students from outside our department.

My contribution to this project specifically focused on data cleaning, multiple imputation, t-tests, multiple regression, and logistic regression. I feel that by doing each of these, considering and testing  their assumptions, and examining diagnostics, gave me a strong grasp of the statistical concepts and my ability to code them in SPSS syntax. I also designed the look and feel of the presentation, especially the color palette, which the audience had a very positive response to (we also wore clothes that matched the colors). Finally, as an additional contribution to this project, I developed an interactive dashboard in Excel for the logistic regression analysis. This was completely supplementary but I learned a lot of advanced Excel skills to be able to do this.

The project was by no means perfect. I was out of town at a conference when the group completed the factor analysis aspect of the assignment. Not being part of that meant I never fully understood what they had done and why, even though I reran their syntax. Factor analysis is both art and science - there are quantitative decisions based on eigenvectors and communalities, but there are also qualitative decisions such as variable inclusion, factor creation, and naming.  I suppose that I was able to reproduce the science of their factor analysis, but not the art, as I was not part of the discussions that could have revealed their logic in decision making. There was too much to do for this project, so I did not ask for more explanation. This is, however, something I should have done, as our factor analysis was one of the areas most criticized in the presentation.

In my opinion, the assignment was perhaps one of the most useful assignments I had ever completed at the time. One reason is because this assignment required us to use nearly every quantitative skill we had learned, from data cleaning to advanced methods (factor analysis, logistic regression). By doing so, it gave us a chance to reinforce and, most importantly, gain confidence in these skills By the end of the assignment, I felt very knowledgeable about each and every method we had utilized.
	
Another reason this was such a beneficial project was because of the group work aspect. Being able to discuss, teach, and give feedback to each others' ideas for analysis and conceptualizations of methods was immensely beneficial. I took on the role of de facto group leader and helped the group stay organized, manage time, and ensure nearly every analysis was done correctly. I will never forget one of the comments a fellow group member left on anonymous group feedback form: “If the Statsketeers were a body – Anthony was the brain”. I feel that taking on this role not only strengthened my quantitative skills, but also my skills to work with and lead a group. Again, this was a valuable assignment, one which has no doubt left a profound impact on my confidence and even leadership skills.

